name: CI for Forum API

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: Lalulilalala27
          POSTGRES_DB: forum_api_test
        options: >-
          --health-cmd="pg_isready -U postgres -d forum_api_test"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Set environment variables
        run: |
          echo "PGHOST=localhost" >> .env
          echo "PGUSER=postgres" >> .env
          echo "PGDATABASE=forum_api_test" >> .env
          echo "PGPASSWORD=Lalulilalala27" >> .env
          echo "PGPORT=5432" >> .env
          

      - name: Wait for PostgreSQL to be ready
        run: |
          until pg_isready -h localhost -p 5432 -U postgres; do
            echo "Waiting for database to be ready..."
            sleep 1
          done

      - name: set Timezone to Jakarta
        run: sudo timedatectl set-timezone Asia/Jakarta

      - name: Run database migrations
        run: npm run migrate:test

      - name: Run tests
        run: npm test
